config/routes.rb
Rails.application.routes.draw do
  
  get    'login'  => 'sessions#new'
  get    'logout' => 'sessions#destroy'
  
  resource :session, only: [:new, :create, :destroy]

  get    'signup'  => 'users#new'
  resource :user, only: [:new, :create]

  get 'dashboard' => 'users#dashboard'

  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user
        can :access
    end    

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/session.rb
class Session
  include ActiveModel::Model

  attr_accessor :name, :password

  attr_reader :user

  validates :name, presence: true
  validates :password, presence: true

  def authenticate?
    if valid?
      @user = lookup
      return true if @user
      errors.add(:name, "might not be correct")
      errors.add(:password, "might not be correct")
    end
    false
  end

  private
  def lookup
    candidate = User.find_by(name: name)
    return candidate if candidate && candidate.authenticate(password)
    nil
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

    before_save { self.name = name.downcase }

	validates :name, presence: true, uniqueness: { case_sensitive: false }

	validates :password, length: { minimum: 8 }, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include CanCan::ControllerAdditions

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  def authenticate_user!
    authorize! :access, nil
  end

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :authenticated?

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def authenticated?
    current_user != nil
  end

  def sign_in(user)
    @current_user = user
    session[:user_id] = user.id
  end

  def log_out
    @current_user = nil
    session.delete :user_id
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @session = Session.new
  end

  def create
    @session = Session.new(session_params)
    if @session.authenticate?
      # Assign to Session
      sign_in(@session.user)
      # Redirect
      redirect_to dashboard_path
    else
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit [:name, :password]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
    	# Assign to Session
    	sign_in(@user)
    	# Redirect
    	redirect_to dashboard_path
    else
      render 'new'
    end
  end

  def dashboard
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:password,:name,:password_confirmation) 
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>Example Rails App with Skeleton</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <%= stylesheet_link_tag    'application', media: 'all' %>

  <!-- Favicon
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>

</head>
<body>

<header>
  <div class="container">
     <% if authenticated? %>
       <div class="message">
         Welcome <%= current_user.name %>! (<%= link_to "Log Out", logout_path %>)
       </div>
     <% else %>
       <div class="actions">
         <%= link_to login_path  do %><button >Log In</button><% end %>
         <%= link_to signup_path  do %><button class="button-primary" >Sign Up</button><% end %>
       </div>
     <% end %>
  </div>
</header>
<div id="content">
<% if flash.any? %>
  <div class="flash">
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
  </div>
<% end -%>


  <!-- Primary Page Layout
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <div class="container">
    <%= yield %>
  </div>
</div>

<!-- End Document
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
<%= javascript_include_tag 'application' %>
</body>
</html>

app/views/users/dashboard.html.erb
<h1>Dashboard</h1>

app/views/users/new.html.erb
<h1>Join Us!</h1>

<%= form_for(@user, url: user_path) do |f| %>
  <div class="row">
    <div class="six columns">
      <%= f.label :name %>
      <% if @user.errors[:name].any? %>
        <span class="field_error">Name <%= @user.errors[:name].first %></span>
      <% end %>
      <%= f.text_field :name, :required => "required", :placeholder => "Username" %>
    </div>
  </div>
  <div class="row">
    <div class="six columns">
      <%= f.label :password %>
      <% if @user.errors[:password].any? %>
        <span class="field_error">Password <%= @user.errors[:password].first %></span>
      <% end %>
      <%= f.password_field :password, :required => "required", :placeholder => "password" %>
    </div>
    <div class="six columns">
      <%= f.label :password_confirmation %>
      <% if @user.errors[:password_confirmation].any? %>
        <span class="field_error">Confirmation <%= @user.errors[:password_confirmation].first %></span>
      <% end %>
      <%= f.password_field :password_confirmation, :required => "required", :placeholder => "password" %>
    </div>
  </div>
  <input class="button-primary" type="submit" value="Register">
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>
<p>Find me in app/views/welcome/index.html.erb</p>